import loginTests
import userinfoTest
import searchTest
import discoverTest
import coreTest
import coreErrorTest
import accompany
import mapTest
import indexTest
import indexErrorTest
import shareTest
import messageTest
import userErrorCheck
